artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/682338566444037820/8086a40ca2c14274b9a1de0f5eb166a2/artifacts
end_time: 1783208770563
entry_point_name: ''
experiment_id: '682338566444037820'
lifecycle_stage: active
run_id: 8086a40ca2c14274b9a1de0f5eb166a2
run_name: one_layer_fcnn
source_name: ''
source_type: 4
source_version: ''
start_time: 1783208700237
status: 3
tags: []
user_id: root
