artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/682338566444037820/e6377d6ac86e4c3bb59a32ecb97a9c2d/artifacts
end_time: 1783209530231
entry_point_name: ''
experiment_id: '682338566444037820'
lifecycle_stage: active
run_id: e6377d6ac86e4c3bb59a32ecb97a9c2d
run_name: two_layer_fcnn
source_name: ''
source_type: 4
source_version: ''
start_time: 1783209188371
status: 3
tags: []
user_id: root
